services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-projecta
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
volumes:
  sql-data:
